# Generated by Django 2.2 on 2020-02-28 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Follow',
        ),
    ]
